#!/usr/bin/env python3
"""Generate the compressed production-data ES module."""

from __future__ import annotations

import base64
import gzip
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent


def encode(path: Path) -> str:
    packed = gzip.compress(path.read_bytes(), compresslevel=9, mtime=0)
    return base64.b64encode(packed).decode("ascii")


def main() -> None:
    kx = encode(ROOT / "assets/debris_party.kx")
    loader = encode(ROOT / "assets/debris_loader.v2m")
    output = (
        "// Generated by tools/embed_assets.py; do not edit.\n"
        f"export const PARTY_KX_GZIP_BASE64 = {kx!r};\n"
        f"export const LOADER_V2M_GZIP_BASE64 = {loader!r};\n"
    )
    (ROOT / "src/debris_data.js").write_text(output)


if __name__ == "__main__":
    main()
