#!/usr/bin/env python3
"""Generate the small deterministic Font3D outline table used by Debris.

This is a maintainer tool, not a runtime dependency. It requires fontTools and
the two pinned OFL-licensed source TTFs described by --help. The output is an
ES module written to stdout so it can be reviewed before replacing
src/font3d_glyphs.js.
"""

from argparse import ArgumentParser
from hashlib import sha256
from json import dumps
from pathlib import Path

from fontTools.ttLib import TTFont


FAMILIES = (
    {
        "key": "arial",
        "source": "Arimo Regular 1.33",
        "commit": "4a6255f269916ae7ad3fc2706b0935e7621396b8",
        "argument": "arimo",
        "characters": ".adefhlmnoprstuvw",
        # CreateFontA receives a positive height. Windows maps that to the
        # Arial character-cell height (usWinAscent + usWinDescent), not to the
        # TrueType em square.
        "units_per_cell": 2288,
        "sha256": "41b22bc8f0b51f932825d37bc55b5eb6ba67dfe599a626e4aff2b43b624f9f8c",
    },
    {
        "key": "georgia",
        "source": "Gelasio Regular 1.008",
        "commit": "7ab20e7e5c42791e603b9ee3201a0b49849cfdb2",
        "argument": "gelasio",
        "characters": " .abcdefghiklmnopqrstuvwxy",
        "units_per_cell": 2327,
        "sha256": "48c797fbe0e07c48a18cb962e7bdfa23f19618327dddf54093265328dc9eb39d",
    },
)


def glyph_record(font, character):
    cmap = font.getBestCmap()
    glyph_name = cmap[ord(character)]
    advance, _left_side_bearing = font["hmtx"][glyph_name]
    glyph = font["glyf"][glyph_name]
    coordinates, endpoints, flags = glyph.getCoordinates(font["glyf"])
    contours = []
    first = 0
    for endpoint in endpoints:
        contour = []
        for index in range(first, endpoint + 1):
            x, y = coordinates[index]
            contour.extend((int(x), int(y), int(bool(flags[index] & 1))))
        contours.append(contour)
        first = endpoint + 1
    return [int(advance), contours]


def quoted(value):
    return dumps(value, ensure_ascii=True, separators=(",", ":"))


def load_font(path, description):
    digest = sha256(path.read_bytes()).hexdigest()
    if digest != description["sha256"]:
        raise ValueError(
            f"{path} has SHA-256 {digest}; expected {description['sha256']}"
        )
    font = TTFont(path, lazy=False)
    if font["head"].unitsPerEm != 2048:
        raise ValueError(f"{path} has unexpected {font['head'].unitsPerEm} units/em")
    return font


def main():
    parser = ArgumentParser(description=__doc__)
    parser.add_argument("--arimo", type=Path, required=True,
                        help="Arimo-Regular.ttf from googlefonts/Arimo commit 4a6255f")
    parser.add_argument("--gelasio", type=Path, required=True,
                        help="Gelasio-Regular.ttf from SorkinType/Gelasio commit 7ab20e7")
    args = parser.parse_args()

    print("// Generated by tools/generate_font3d_glyphs.py. Do not edit by hand.")
    print("// The compact subsets are OFL-1.1 Font Software; see vendor/font3d/LICENSE.txt.")
    print("const FONT3D_FAMILIES = {")
    for family_index, description in enumerate(FAMILIES):
        font = load_font(getattr(args, description["argument"]), description)
        print(f"  {quoted(description['key'])}: {{")
        print(f"    source: {quoted(description['source'])},")
        print(f"    sourceCommit: {quoted(description['commit'])},")
        print(f"    sourceSHA256: {quoted(description['sha256'])},")
        print(f"    unitsPerCell: {description['units_per_cell']},")
        print("    glyphs: {")
        for index, character in enumerate(description["characters"]):
            suffix = "," if index + 1 < len(description["characters"]) else ""
            print(f"      {quoted(character)}: {quoted(glyph_record(font, character))}{suffix}")
        print("    }")
        suffix = "," if family_index + 1 < len(FAMILIES) else ""
        print(f"  }}{suffix}")
        font.close()
    print("};")
    print("")
    print("export { FONT3D_FAMILIES };")


if __name__ == "__main__":
    main()
