import { readFile, writeFile } from 'node:fs/promises';

const sourceUrl = new URL('../notes/debris_js_dispatch.json', import.meta.url);
const outputUrl = new URL('../src/classes.js', import.meta.url);
const rows = JSON.parse(await readFile(sourceUrl, 'utf8'));

const registry = {};
for (const row of rows) {
  registry[row.id] = {
    id: row.id,
    name: row.name,
    convention: Number.parseInt(row.convention, 16) >>> 0,
    dataWords: row.dataWords,
    inputSlots: row.inputSlots,
    linkSlots: row.linkSlots,
    stringSlots: row.stringSlots,
    splineSlots: row.splineSlots,
    packingOverrunWords: row.packingOverrunWords,
    outputClass: row.outputClass,
    init: row.initHandler,
    exec: row.execHandler,
    dynamic: row.dynamic,
  };
}

const output = `// Generated by tools/generate_classes.mjs; do not edit.\n` +
  `export const CLASS_REGISTRY = ${JSON.stringify(registry, null, 2)};\n`;

await writeFile(outputUrl, output);
