import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { CLASS_REGISTRY } from '../src/classes.js';
import {
  compressDxt5Block,
  decodeDxt5Block,
  dxt5LevelByteLength,
  dxt5MipChainByteLength,
  dxt5MipLevelCount,
  forEachDxt5Mip,
} from '../src/dxt5.js';
import { parseKX } from '../src/kx.js';

const hex = bytes => Array.from(bytes, byte => byte.toString(16).padStart(2, '0')).join('');
const block = new Uint8Array(64);
const setPixel = (index, red, green, blue, alpha) => {
  const offset = index * 4;
  block[offset] = blue;
  block[offset + 1] = green;
  block[offset + 2] = red;
  block[offset + 3] = alpha;
};
const assertBlock = (name, expected) => {
  assert.equal(hex(compressDxt5Block(block)), expected, `${name} matches vendored rygdxt`);
};

// These byte vectors and the aggregate hash were generated by compiling the
// unmodified vendor/wz3/base/_rygdxt.cpp quality-0 path in a temporary C++
// oracle. They cover constant-color OMatch tables, alpha packing, PCA,
// endpoint refinement, and mixed RGB/alpha input.
for (let i = 0; i < 16; i++) setPixel(i, 0, 0, 0, 0);
assertBlock('transparent black', '000049922449922400000000aaaaaaaa');
for (let i = 0; i < 16; i++) setPixel(i, 255, 255, 255, 255);
assertBlock('opaque white', 'ffff499224499224ffffffffaaaaaaaa');
for (let i = 0; i < 16; i++) setPixel(i, 18, 52, 86, 120);
assertBlock('constant rgba', '7878499224499224ef192109aaaaaaaa');
for (let y = 0; y < 4; y++) for (let x = 0; x < 4; x++) {
  const index = y * 4 + x;
  setPixel(index, x * 73 + y * 11, y * 61 + x * 7, (x + y) * 31, index * 17);
}
assertBlock('rgba ramp', 'ff00c96fb7e4260135fd2201b5ad2f2b');

let randomState = 0x12345678;
const randomByte = () => {
  randomState = (Math.imul(randomState, 1664525) + 1013904223) >>> 0;
  return randomState >>> 24;
};
for (let i = 0; i < 16; i++) {
  setPixel(i, randomByte(), randomByte(), randomByte(), randomByte());
}
assertBlock('seeded mixed block', 'f214466b502d632945b1995de76d1e20');

randomState = 0x6d2b79f5;
let hash = 0x811c9dc5;
const encoded = new Uint8Array(16);
for (let iteration = 0; iteration < 4096; iteration++) {
  for (let i = 0; i < 16; i++) {
    setPixel(i, randomByte(), randomByte(), randomByte(), randomByte());
  }
  compressDxt5Block(block, encoded);
  for (const byte of encoded) hash = Math.imul(hash ^ byte, 0x01000193) >>> 0;
}
assert.equal(hash, 0x17a3de76, '4096 seeded blocks match the C encoder hash');

function write16(bytes, offset, value) {
  bytes[offset] = value & 255;
  bytes[offset + 1] = value >>> 8;
}

function packIndices(bytes, offset, width, indices) {
  for (let index = 0; index < indices.length; index++) {
    for (let bit = 0; bit < width; bit++) {
      if (indices[index] & (1 << bit)) {
        const destination = index * width + bit;
        bytes[offset + (destination >> 3)] |= 1 << (destination & 7);
      }
    }
  }
}

// BC3 always uses the opaque four-color RGB palette. Its alpha half has two
// endpoint-order modes; lock all indices for both modes independently.
const handBlock = new Uint8Array(16);
handBlock[0] = 255;
handBlock[1] = 0;
packIndices(handBlock, 2, 3, Array.from({ length: 16 }, (_, index) => index & 7));
write16(handBlock, 8, 0xf800); // red
write16(handBlock, 10, 0x001f); // blue
packIndices(handBlock, 12, 2, Array.from({ length: 16 }, (_, index) => index & 3));
let decoded = decodeDxt5Block(handBlock);
assert.deepEqual(Array.from(decoded.slice(0, 16)), [
  255, 0, 0, 255,
  0, 0, 255, 0,
  170, 0, 85, 219,
  85, 0, 170, 182,
]);
assert.deepEqual(Array.from(decoded).filter((_, index) => (index & 3) === 3).slice(0, 8),
  [255, 0, 219, 182, 146, 109, 73, 36]);

handBlock.fill(0);
handBlock[0] = 0;
handBlock[1] = 255;
packIndices(handBlock, 2, 3, Array.from({ length: 16 }, (_, index) => index & 7));
write16(handBlock, 8, 0x001f); // endpoint0 blue is numerically below red
write16(handBlock, 10, 0xf800);
packIndices(handBlock, 12, 2, new Array(16).fill(3));
decoded = decodeDxt5Block(handBlock);
assert.deepEqual(Array.from(decoded.slice(0, 4)), [170, 0, 85, 0],
  'BC3 endpoint order never selects BC1 transparent black');
assert.deepEqual(Array.from(decoded).filter((_, index) => (index & 3) === 3).slice(0, 8),
  [0, 255, 51, 102, 153, 204, 0, 255]);

const mipWords = new Uint16Array(4 * 4 * 4);
for (let y = 0; y < 4; y++) for (let x = 0; x < 4; x++) {
  const offset = (y * 4 + x) * 4;
  mipWords[offset] = ((x * 37 + y * 11) << 7) | ((x * 17 + y * 29) & 127);
  mipWords[offset + 1] = ((x * 13 + y * 47) << 7) | ((x * 31 + y * 7) & 127);
  mipWords[offset + 2] = ((x * 53 + y * 19) << 7) | ((x * 5 + y * 43) & 127);
  mipWords[offset + 3] = (((x + y) * 29 + 32) << 7) | ((x * 23 + y * 37) & 127);
}
const mipBitmap = {
  width: 4, height: 4, format: 9, texMipCount: 0, texMipThreshold: 0,
  data: mipWords,
};
const mipHex = [];
const mipBuffers = [];
assert.equal(forEachDxt5Mip(mipBitmap, 'bc3', (level, width, height, bytes) => {
  mipHex.push([level, width, height, hex(bytes)]);
  mipBuffers.push(bytes.buffer);
}), 3);
assert.deepEqual(mipHex, [
  [0, 4, 4, 'ce20b97b77eed409da8ce100b5ad2f2b'],
  [1, 2, 2, 'b13d695a14695a14367c641999339933'],
  [2, 1, 1, '7777499224499224f36ba100aaaaaaaa'],
], '16-bit box-filtered mips and wrapped sub-4 blocks match the C oracle');
assert.equal(new Set(mipBuffers).size, 1, 'compressed levels reuse one bounded output buffer');

// JS Bitmap storage is logical RGBA, whereas rygdxt's Pixel union is BGRA.
// A pure-red source catches an accidental first/third-channel gather swap.
const redWords = new Uint16Array(4 * 4 * 4);
for (let offset = 0; offset < redWords.length; offset += 4) {
  redWords[offset] = 0x7fff;
  redWords[offset + 3] = 0x7fff;
}
const redLevels = [];
forEachDxt5Mip({ ...mipBitmap, data: redWords }, 'rgba8',
  (level, width, height, bytes) => redLevels.push({ level, width, height, bytes: Array.from(bytes) }));
assert.deepEqual(redLevels.map(({ level, width, height }) => [level, width, height]),
  [[0, 4, 4], [1, 2, 2], [2, 1, 1]]);
for (const level of redLevels) {
  for (let offset = 0; offset < level.bytes.length; offset += 4) {
    assert.deepEqual(level.bytes.slice(offset, offset + 4), [255, 0, 0, 255]);
  }
}

assert.equal(dxt5LevelByteLength(512, 512), 262144);
assert.equal(dxt5LevelByteLength(2, 1), 16);
assert.equal(dxt5MipLevelCount({ width: 512, height: 512, texMipCount: 0 }), 10);
assert.equal(dxt5MipChainByteLength(512, 512, 10), 349552);
assert.throws(() => forEachDxt5Mip({ ...mipBitmap, texMipThreshold: 64 }, 'bc3', () => {}),
  /quality-0/);

// Production inventory: exactly five authored Format9 nodes, all quality-0,
// all full-chain, and every dimension-bearing bitmap leaf resolves to 9x9.
const document = parseKX(await readFile(new URL('../assets/debris_party.kx', import.meta.url)));
const format9 = document.operations.filter(operation =>
  operation.classId === 0x25 && operation.parameters[0] === 9);
assert.deepEqual(format9.map(operation => operation.id), [2190, 11360, 12575, 12634, 12666]);
for (const operation of format9) assert.deepEqual(operation.parameters, [9, 0, 0]);

const sizedGenerators = new Set([0x21, 0x22, 0x32, 0x34, 0x3d]);
const dimensionMemo = new Map();
function bitmapDimensions(operationId) {
  if (dimensionMemo.has(operationId)) return dimensionMemo.get(operationId);
  const operation = document.operations[operationId];
  if (sizedGenerators.has(operation.classId)) {
    const result = [1 << (operation.parameters[0] & 0x7f), 1 << (operation.parameters[1] & 0x7f)];
    dimensionMemo.set(operationId, result);
    return result;
  }
  const inputDimensions = operation.inputs
    .filter(input => CLASS_REGISTRY[document.operations[input].classId]?.outputClass === 'KC_BITMAP')
    .map(bitmapDimensions).filter(Boolean);
  const result = inputDimensions[0] || null;
  for (const dimensions of inputDimensions.slice(1)) assert.deepEqual(dimensions, result,
    `bitmap op ${operationId} inputs retain matching dimensions`);
  dimensionMemo.set(operationId, result);
  return result;
}
assert.deepEqual(format9.map(operation => bitmapDimensions(operation.inputs[0])),
  new Array(5).fill(null).map(() => [512, 512]));

console.log('DXT5 codec, mip, and production inventory tests passed');
