import assert from 'node:assert/strict';
import {
  LEGACY_ATTENUATION_VOLUME_BYTE_LENGTH,
  LEGACY_ATTENUATION_VOLUME_SIZE,
  LEGACY_NORMALIZER_CUBE_BYTE_LENGTH,
  LEGACY_NORMALIZER_CUBE_SIZE,
  LEGACY_NORMALIZER_FACE_BYTE_LENGTH,
  LEGACY_NORMALIZER_FACE_ORDER,
  legacyCubeNormalizerFace,
  makeLegacyAttenuationVolume,
  makeLegacyCubeNormalizer,
} from '../src/legacy_lookup.js';

function fnv1a(bytes) {
  let hash = 0x811c9dc5;
  for (const byte of bytes) hash = Math.imul(hash ^ byte, 0x01000193) >>> 0;
  return hash;
}

function rgba2d(bytes, width, x, y) {
  const offset = (y * width + x) * 4;
  return Array.from(bytes.subarray(offset, offset + 4));
}

function rgba3d(bytes, size, x, y, z) {
  const offset = ((z * size + y) * size + x) * 4;
  return Array.from(bytes.subarray(offset, offset + 4));
}

assert.equal(LEGACY_NORMALIZER_CUBE_SIZE, 64);
assert.equal(LEGACY_NORMALIZER_FACE_BYTE_LENGTH, 64 * 64 * 4);
assert.equal(LEGACY_NORMALIZER_CUBE_BYTE_LENGTH, 6 * 64 * 64 * 4);
assert.deepEqual(LEGACY_NORMALIZER_FACE_ORDER,
  ['positive-x', 'negative-x', 'positive-y', 'negative-y', 'positive-z', 'negative-z']);

const cube = makeLegacyCubeNormalizer();
assert.equal(cube.byteLength, 98304);
const faces = Array.from({ length: 6 }, (_, index) =>
  legacyCubeNormalizerFace(cube, index));
assert.deepEqual(faces.map(face => face.byteLength), new Array(6).fill(16384));
assert.equal(faces[0].buffer, cube.buffer, 'face views must not copy the cube allocation');
assert.deepEqual(rgba2d(faces[0], 64, 0, 0), [201, 201, 201, 0]);
assert.deepEqual(rgba2d(faces[0], 64, 63, 0), [201, 201, 55, 0]);
assert.deepEqual(rgba2d(faces[0], 64, 0, 63), [201, 55, 201, 0]);
assert.deepEqual(rgba2d(faces[0], 64, 31, 31), [255, 130, 130, 0]);
assert.deepEqual(rgba2d(faces[0], 64, 32, 32), [255, 126, 126, 0]);

// Opposite faces encode opposite directions at mirrored texels. Because the
// signed encoding is 128 + n*127, opposite RGB byte pairs sum to 256.
for (const [a, b, mirrorX, mirrorY] of [
  [0, 1, false, true],
  [2, 3, true, false],
  [4, 5, false, true],
]) {
  for (let y = 0; y < 64; y += 7) for (let x = 0; x < 64; x += 5) {
    const left = rgba2d(faces[a], 64, x, y);
    const right = rgba2d(faces[b], 64, mirrorX ? 63 - x : x,
      mirrorY ? 63 - y : y);
    assert.deepEqual(left.slice(0, 3).map((value, channel) => value + right[channel]),
      [256, 256, 256]);
  }
}

// Generated by tools/oracles/legacy_lookup_oracle.cpp, which independently
// compiles the released algorithms with float stores and FE_TONEAREST.
assert.equal(fnv1a(cube), 0x98a49365, 'cube matches the source-derived C oracle');
assert.deepEqual(faces.map(fnv1a), [
  0x8abd2b05, 0xa48c49f5, 0xed11d631,
  0x97aab909, 0x97cf55bd, 0x37b9878d,
], 'each oriented face matches the C oracle');

const suppliedCube = new Uint8Array(LEGACY_NORMALIZER_CUBE_BYTE_LENGTH);
assert.equal(makeLegacyCubeNormalizer(suppliedCube), suppliedCube);
assert.throws(() => makeLegacyCubeNormalizer(new Uint8Array(4)), /98304-byte/);
assert.throws(() => legacyCubeNormalizerFace(cube, 6), /0 to 5/);

assert.equal(LEGACY_ATTENUATION_VOLUME_SIZE, 32);
assert.equal(LEGACY_ATTENUATION_VOLUME_BYTE_LENGTH, 32 ** 3 * 4);
const volume = makeLegacyAttenuationVolume();
assert.equal(volume.byteLength, 131072);
assert.deepEqual(rgba3d(volume, 32, 16, 16, 16), [255, 255, 255, 255]);
assert.deepEqual(rgba3d(volume, 32, 15, 16, 16), [254, 254, 254, 254]);
assert.deepEqual(rgba3d(volume, 32, 1, 16, 16), [0, 0, 0, 0]);
assert.deepEqual(rgba3d(volume, 32, 31, 16, 16), [0, 0, 0, 0]);
assert.deepEqual(rgba3d(volume, 32, 16, 16, 0), [0, 0, 0, 0]);
// material11.cpp sets ADDRESSU/V/W to D3DTADDRESS_CLAMP. Coordinates outside
// the volume therefore resolve to one of these edge texels, all of which must
// stay black rather than extending a face-centre light streak.
for (let axis = 0; axis < 3; axis++) for (const edge of [0, 31]) {
  for (let a = 0; a < 32; a++) for (let b = 0; b < 32; b++) {
    const coordinate = [0, 0, 0];
    coordinate[axis] = edge;
    coordinate[(axis + 1) % 3] = a;
    coordinate[(axis + 2) % 3] = b;
    assert.deepEqual(rgba3d(volume, 32, ...coordinate), [0, 0, 0, 0],
      `clamped attenuation boundary axis ${axis} edge ${edge} stays black`);
  }
}
for (let z = 0; z < 32; z += 3) for (let y = 0; y < 32; y += 5) {
  for (let x = 1; x < 32; x += 7) {
    assert.deepEqual(rgba3d(volume, 32, x, y, z),
      rgba3d(volume, 32, 32 - x, y, z), 'volume is symmetric around texel 16');
  }
}
assert.equal(fnv1a(volume), 0x20208279,
  'attenuation volume matches the source-derived C oracle');

const suppliedVolume = new Uint8Array(LEGACY_ATTENUATION_VOLUME_BYTE_LENGTH);
assert.equal(makeLegacyAttenuationVolume(suppliedVolume), suppliedVolume);
assert.throws(() => makeLegacyAttenuationVolume(new Uint8Array(4)), /131072-byte/);

console.log('legacy Material11 lookup texture tests passed');
